  <div class="container">
    <h1>Home</h1>
    <img class="img-fluid img-thumbnail" src="https://unsplash.it/1200/900">
    <div class="row">
      <p class="col-sm">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, beatae, nihil delectus iusto facere maiores harum. Necessitatibus distinctio eveniet earum molestias incidunt magni ut culpa!</p>
      <p class="col-sm">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, beatae, nihil delectus iusto facere maiores harum. Necessitatibus distinctio eveniet earum molestias incidunt magni ut culpa!</p>
    </div>
  </div>