  
  <div class="container">
    <h1>Login</h1>
    <form action="./index.php" method="post">
      <div class="form-group mb-2">
        <label for="email" class="input-label">Email</label>
        <input id="email" type="email" name="email" class="form-control" placeholder="Entrez votre email" />
      </div>
      <div class="form-group mb-2">
        <label for="name" class="input-label">Prenom</label>
        <input id="name" type="text" name="firstname" class="form-control" placeholder="Entrez votre prenom" />
      </div>
      <input type="submit" name="submit" value="S'inscrire" class="btn btn-primary"  />
    </form>
    <p>Vous n'avez pas de compte ? <a class="link-primary" href="?action=register">Inscrivez-vous</a></p>
  </div>