  <h1>Register</h1>
  
  <div class="container">
    <form action="./index.php" method="post">
      <div class="form-group">
        <label for="fname" class="input-label">Nom</label>
        <input id="fname" type="text" name="firstname" class="form-control" placeholder="Entrez votre nom" />
      </div>
      <div class="form-group">
        <label for="lname" class="input-label">Prenom</label>
        <input id="lname" type="text" name="lastname" class="form-control" placeholder="Entrez votre prenom" />
      </div>
      <div class="form-group">
        <label for="email" class="input-label">Email</label>
        <input id="email" type="text" name="email" class="form-control" placeholder="Entrez votre addresse email" />
      </div>
      <div class="form-group">
        <label for="tel" class="input-label">Telephone</label>
        <input id="tel" type="text" name="telephone" class="form-control" placeholder="Entrez votre numero de telephone" />
      </div>
      <input type="submit" name="submit" value="S'inscrire" class="btn btn-primary"  />
    </form>
  </div>